CREATE TABLE IF NOT EXISTS events (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    handler VARCHAR(100) NOT NULL DEFAULT '',
    type VARCHAR(20) NOT NULL DEFAULT '',
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    name VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL DEFAULT '',
    discord VARCHAR(500) NOT NULL DEFAULT '',
    banner_url VARCHAR(1000) NOT NULL DEFAULT '',
    banner_pos_x TINYINT UNSIGNED NOT NULL DEFAULT 50,
    banner_pos_y TINYINT UNSIGNED NOT NULL DEFAULT 50,
    banner_zoom DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    description TEXT NOT NULL,
    property_id VARCHAR(50) NOT NULL,
    notes TEXT NOT NULL,
    PRIMARY KEY (id),
    KEY idx_event_date (event_date),
    KEY idx_status (status)
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(50) NOT NULL,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (setting_key)
);

CREATE TABLE IF NOT EXISTS environmental_events (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    event_id VARCHAR(50) NOT NULL DEFAULT '',
    weight TINYINT UNSIGNED NOT NULL DEFAULT 5,
    faction_flags VARCHAR(255) NOT NULL DEFAULT '',
    type VARCHAR(50) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL DEFAULT '',
    banner_url VARCHAR(1000) NOT NULL DEFAULT '',
    banner_pos_x TINYINT UNSIGNED NOT NULL DEFAULT 50,
    banner_pos_y TINYINT UNSIGNED NOT NULL DEFAULT 50,
    banner_zoom DECIMAL(4,2) NOT NULL DEFAULT 1.00,
    label TEXT NOT NULL,
    PRIMARY KEY (id),
    KEY idx_env_name (name),
    KEY idx_env_weight (weight)
);
